### ISSUE TITLE
Update to match jrosservices?

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/jros2actionlib#1]
Tried making a new action, but the action factory class seems to use an outdated version of your jrosservices package. Specifically, it seems as if `import pinorobotics.jros2services.service_msgs.ServiceDefinition` has moved to `package pinorobotics.jrosservices.msgs.ServiceDefinition`. If this is a relatively easy fix, I'm happy to fix it and make a pull request.

**Comment by aeon9** [comment]
Hi @marlow-fawn 

Thanks for reporting it.

You right the jros2actionlib with new jros2services was not yet released. I have released it now so you can try [version 2](https://github.com/pinorobotics/jros2actionlib/blob/main/jros2actionlib/release/CHANGELOG.md)

Regards,
